package com.example.model

import androidx.compose.ui.graphics.Color

data class GameLevel(
    val id: String,
    val name: String,
    val subtitle: String,
    val unlockCost: Int,
    val difficulty: String,
    val gravity: Float = 9.8f,
    val surfaceFriction: Float = 1.0f,
    val hillAmplitudeMultiplier: Float = 1.0f,
    val hillFrequencyMultiplier: Float = 1.0f,
    val skyTopColor: Color,
    val skyBottomColor: Color,
    val terrainTopColor: Color,
    val terrainBottomColor: Color,
    val surfaceAccentColor: Color,
    val distantMountainColor: Color,
    val particleColor: Color
) {
    companion object {
        val ALL_LEVELS = listOf(
            GameLevel(
                id = "green_hills",
                name = "Green Hills",
                subtitle = "Rolling meadows & gentle ramps",
                unlockCost = 0,
                difficulty = "Beginner",
                gravity = 9.8f,
                surfaceFriction = 1.0f,
                hillAmplitudeMultiplier = 0.9f,
                hillFrequencyMultiplier = 0.85f,
                skyTopColor = Color(0xFF1565C0),
                skyBottomColor = Color(0xFF64B5F6),
                terrainTopColor = Color(0xFF2E7D32),
                terrainBottomColor = Color(0xFF1B5E20),
                surfaceAccentColor = Color(0xFF81C784),
                distantMountainColor = Color(0x551E40AF),
                particleColor = Color(0xFF8D6E63)
            ),
            GameLevel(
                id = "rocky_mountains",
                name = "Rocky Mountains",
                subtitle = "Steep jagged cliffs & dangerous drops",
                unlockCost = 500,
                difficulty = "Medium",
                gravity = 10.2f,
                surfaceFriction = 0.95f,
                hillAmplitudeMultiplier = 1.25f,
                hillFrequencyMultiplier = 1.1f,
                skyTopColor = Color(0xFF37474F),
                skyBottomColor = Color(0xFF78909C),
                terrainTopColor = Color(0xFF5D4037),
                terrainBottomColor = Color(0xFF3E2723),
                surfaceAccentColor = Color(0xFF8D6E63),
                distantMountainColor = Color(0x66455A64),
                particleColor = Color(0xFFBCAAA4)
            ),
            GameLevel(
                id = "desert_dunes",
                name = "Desert",
                subtitle = "Sinking sand dunes & heat shimmer",
                unlockCost = 1200,
                difficulty = "Hard",
                gravity = 9.6f,
                surfaceFriction = 0.82f,
                hillAmplitudeMultiplier = 1.15f,
                hillFrequencyMultiplier = 0.95f,
                skyTopColor = Color(0xFFE65100),
                skyBottomColor = Color(0xFFFFB74D),
                terrainTopColor = Color(0xFFF57C00),
                terrainBottomColor = Color(0xFFE65100),
                surfaceAccentColor = Color(0xFFFFE082),
                distantMountainColor = Color(0x55BF360C),
                particleColor = Color(0xFFFFCC80)
            ),
            GameLevel(
                id = "snow_valley",
                name = "Snow Valley",
                subtitle = "Icy glaciers & slick snow crests",
                unlockCost = 2500,
                difficulty = "Expert",
                gravity = 9.8f,
                surfaceFriction = 0.72f,
                hillAmplitudeMultiplier = 1.35f,
                hillFrequencyMultiplier = 1.0f,
                skyTopColor = Color(0xFF283593),
                skyBottomColor = Color(0xFF9FA8DA),
                terrainTopColor = Color(0xFFE0F7FA),
                terrainBottomColor = Color(0xFF80DEEA),
                surfaceAccentColor = Color(0xFFFFFFFF),
                distantMountainColor = Color(0x661A237E),
                particleColor = Color(0xFFFFFFFF)
            ),
            GameLevel(
                id = "volcano_crag",
                name = "Volcano",
                subtitle = "Molten ridges & hazardous volcanic ash",
                unlockCost = 5000,
                difficulty = "Insane",
                gravity = 10.5f,
                surfaceFriction = 0.88f,
                hillAmplitudeMultiplier = 1.45f,
                hillFrequencyMultiplier = 1.2f,
                skyTopColor = Color(0xFF212121),
                skyBottomColor = Color(0xFFD84315),
                terrainTopColor = Color(0xFFBF360C),
                terrainBottomColor = Color(0xFF3E2723),
                surfaceAccentColor = Color(0xFFFF5722),
                distantMountainColor = Color(0x66BF360C),
                particleColor = Color(0xFFFF7043)
            ),
            GameLevel(
                id = "night_highway",
                name = "Night Highway",
                subtitle = "Cyber neon skyline & hyper speed ramps",
                unlockCost = 10000,
                difficulty = "Extreme",
                gravity = 9.8f,
                surfaceFriction = 1.15f,
                hillAmplitudeMultiplier = 1.4f,
                hillFrequencyMultiplier = 1.3f,
                skyTopColor = Color(0xFF0D1B2A),
                skyBottomColor = Color(0xFF1B263B),
                terrainTopColor = Color(0xFF00E5FF),
                terrainBottomColor = Color(0xFF0F172A),
                surfaceAccentColor = Color(0xFF00FFFF),
                distantMountainColor = Color(0x7700E5FF),
                particleColor = Color(0xFF80D8FF)
            )
        )
    }
}
